### PR TITLE
fixed header and sending messages by enter

### PR DESCRIPTION
**Pull request by Zoomskij**
Fixed header, added sendig messages by enter and also added auto scroll to the last message in the chat

### CODE REVIEW

**Comment by kirill-782** [comment]
Should there be horizontal scrolling in the chat list? Or is this a bug?

**Comment by kirill-782** [comment]
image

**Comment by Zoomskij** [comment]
Поправил
image

**Comment by kirill-782** [comment]
Обновлю сайт когда руки дойдут

**Pull request merged**
